### ISSUE TITLE
Crash likely due to high solicitation of the playback trigger?

### ISSUE THREAD

**Issue by julieelie** [siriuslee/pyoperant#1]
Hello Tyler,

I encountered that problem several times these past weeks: the subject is activating multiple times the playback trigger, maybe too fast, and the code crashes. In the present test, there are only a few unrewarded stims (dozen) and 2 rewarded stims. So the code is likely to call the same stimulus in consecutive trials.  The python error I get is:

`"2016-10-01 11:58:45,084","INFO","Trial 99 - 11:58:45 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_2.wav"
"2016-10-01 11:58:46,146","INFO","Finishing session 1 at Sat Oct  1 11:58:46 2016"
"2016-10-01 11:58:46,146","INFO","Finished all sessions."
"2016-10-01 11:58:46,461","INFO","Exiting Session state"
"2016-10-01 11:58:46,461","CRITICAL","IOError('close() called during concurrent operation on the same file object.',)"
"2016-10-01 11:58:46,461","INFO","Exiting Idle state"
"2016-10-01 11:58:46,461","CRITICAL","IOError('close() called during concurrent operation on the same file object.',)"
"2016-10-01 11:58:46,468","ERROR","Unhandled exception: Traceback (most recent call last):
  File "/home/fet/scripts/pecking_test", line 171, in <module>
    args.func(args)
  File "/home/fet/scripts/pecking_test", line 15, in run
    run_pecking_test(args)
  File "/home/fet/python_path/pyoperant/tlab/pecking_test.py", line 192, in run_pecking_test
    exp.run()
  File "/home/fet/python_path/pyoperant/behavior/base.py", line 548, in run
    self._idle.start()
  File "/home/fet/python_path/pyoperant/states.py", line 95, in start
    state.run()
  File "/home/fet/python_path/pyoperant/states.py", line 180, in run
    return self.experiment.session.start()
  File "/home/fet/python_path/pyoperant/states.py", line 95, in start
    state.run()
  File "/home/fet/python_path/pyoperant/states.py", line 137, in run
    self.experiment.session_main()
  File "/home/fet/python_path/pyoperant/behavior/base.py", line 572, in session_main
    trial.run()
  File "/home/fet/python_path/pyoperant/trials.py", line 117, in run
    self.experiment.response_main()
  File "/home/fet/python_path/pyoperant/behavior/go_no_go_interrupt.py", line 141, in response_main
    self.panel.speaker.stop()
  File "/home/fet/python_path/pyoperant/components.py", line 587, in stop
    return self.output.stop(event=self.event)
  File "/home/fet/python_path/pyoperant/hwio.py", line 431, in stop
    return self.interface._stop_wav(event=event, **self.params)
  File "/home/fet/python_path/pyoperant/interfaces/pyaudio_.py", line 155, in _stop_wav
    self.wf.close()
  File "/home/fet/anaconda2/envs/pecking_test/lib/python2.7/wave.py", line 187, in close
    file.close()
IOError: close() called during concurrent operation on the same file object.`

Thank you for your help!
J

**Comment by siriuslee** [comment]
Interesting. Could you post a bit larger chunk of the log file? I'd like to see if that same stimulus was played the trial before and at what time. 

Looking at the `interfaces/pyaudio_.py` code, it looks like we should be calling `self.stream.stop_stream()` before attempting to close the stream or the wav file. See: https://people.csail.mit.edu/hubert/pyaudio/docs/. Fixing that might do away with the problem.

**Comment by julieelie** [comment]
Here is the whole output of the session:
`(pecking_test)fet@chubbyninja:~$ pecking_test run 5
Called run_pecking_test
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
"2016-10-01 11:36:08,590","INFO","Preparing subject and data storage"
"2016-10-01 11:36:08,590","INFO","Created subject object with name LblGra2826F"
"2016-10-01 11:36:08,590","INFO","Created datastore CSVStore: filename = /home/fet/data/LblGra2826F/011016/LblGra2826F_trialdata_20161001113608.csv, fields = session, index, time, stimulus_name, condition_name, response, correct, rt, reward, max_wait for subject LblGra2826F"
"2016-10-01 11:36:08,591","INFO","Preparing to run experiment Go No-Go Interruption"
"2016-10-01 11:36:08,896","INFO","Entering Idle state"
"2016-10-01 11:36:09,205","INFO","Beginning block #1"
"2016-10-01 11:36:18,063","INFO","Trial 1 - 11:36:18 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_11.wav"
"2016-10-01 11:36:40,636","INFO","Trial 2 - 11:36:40 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_12.wav"
"2016-10-01 11:36:40,703","INFO","Trial 3 - 11:36:40 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_1.wav"
"2016-10-01 11:37:07,717","INFO","Trial 4 - 11:37:07 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_9.wav"
"2016-10-01 11:37:13,726","INFO","Supplying reward for 12.00 seconds"
"2016-10-01 11:38:52,316","INFO","Trial 5 - 11:38:52 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_11.wav"
"2016-10-01 11:40:01,629","INFO","Trial 6 - 11:40:01 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_7.wav"
"2016-10-01 11:40:01,693","INFO","Trial 7 - 11:40:01 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_10.wav"
"2016-10-01 11:40:30,214","INFO","Trial 8 - 11:40:30 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_10.wav"
"2016-10-01 11:40:54,723","INFO","Trial 9 - 11:40:54 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_8.wav"
"2016-10-01 11:40:54,779","INFO","Trial 10 - 11:40:54 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_17.wav"
"2016-10-01 11:41:12,024","INFO","Trial 11 - 11:41:12 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_2.wav"
"2016-10-01 11:41:12,252","INFO","Trial 12 - 11:41:12 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_1.wav"
"2016-10-01 11:41:22,824","INFO","Trial 13 - 11:41:22 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_12.wav"
"2016-10-01 11:41:37,024","INFO","Trial 14 - 11:41:37 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_1.wav"
"2016-10-01 11:41:37,092","INFO","Trial 15 - 11:41:37 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_2.wav"
"2016-10-01 11:41:38,076","INFO","Trial 16 - 11:41:38 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_2.wav"
"2016-10-01 11:41:59,703","INFO","Trial 17 - 11:41:59 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_12.wav"
"2016-10-01 11:42:14,030","INFO","Trial 18 - 11:42:14 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_10.wav"
"2016-10-01 11:42:22,709","INFO","Trial 19 - 11:42:22 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_2.wav"
"2016-10-01 11:42:23,936","INFO","Trial 20 - 11:42:23 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_1.wav"
"2016-10-01 11:42:30,364","INFO","Trial 21 - 11:42:30 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_10.wav"
"2016-10-01 11:42:30,518","INFO","Trial 22 - 11:42:30 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_17.wav"
"2016-10-01 11:42:30,997","INFO","Trial 23 - 11:42:30 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_12.wav"
"2016-10-01 11:42:43,073","INFO","Trial 24 - 11:42:43 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_11.wav"
"2016-10-01 11:42:43,149","INFO","Trial 25 - 11:42:43 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_9.wav"
"2016-10-01 11:42:46,914","INFO","Trial 26 - 11:42:46 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_1.wav"
"2016-10-01 11:42:54,714","INFO","Trial 27 - 11:42:54 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_2.wav"
"2016-10-01 11:43:18,060","INFO","Trial 28 - 11:43:18 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_2.wav"
"2016-10-01 11:43:18,144","INFO","Trial 29 - 11:43:18 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_11.wav"
"2016-10-01 11:43:37,638","INFO","Trial 30 - 11:43:37 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_12.wav"
"2016-10-01 11:43:37,714","INFO","Trial 31 - 11:43:37 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_1.wav"
"2016-10-01 11:43:46,567","INFO","Trial 32 - 11:43:46 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_12.wav"
"2016-10-01 11:43:57,023","INFO","Trial 33 - 11:43:57 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_1.wav"
"2016-10-01 11:44:12,694","INFO","Trial 34 - 11:44:12 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_8.wav"
"2016-10-01 11:44:13,753","INFO","Trial 35 - 11:44:13 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_2.wav"
"2016-10-01 11:44:21,032","INFO","Trial 36 - 11:44:21 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_12.wav"
"2016-10-01 11:44:21,105","INFO","Trial 37 - 11:44:21 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_10.wav"
"2016-10-01 11:44:21,408","INFO","Trial 38 - 11:44:21 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_7.wav"
"2016-10-01 11:44:21,481","INFO","Trial 39 - 11:44:21 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_11.wav"
"2016-10-01 11:44:34,897","INFO","Trial 40 - 11:44:34 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_12.wav"
"2016-10-01 11:44:34,964","INFO","Trial 41 - 11:44:34 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_9.wav"
"2016-10-01 11:44:40,972","INFO","Supplying reward for 12.00 seconds"
"2016-10-01 11:46:07,196","INFO","Trial 42 - 11:46:07 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_2.wav"
"2016-10-01 11:46:32,725","INFO","Trial 43 - 11:46:32 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_10.wav"
"2016-10-01 11:46:32,785","INFO","Trial 44 - 11:46:32 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_8.wav"
"2016-10-01 11:46:38,799","INFO","Supplying reward for 12.00 seconds"
"2016-10-01 11:48:03,168","INFO","Trial 45 - 11:48:03 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_7.wav"
"2016-10-01 11:48:09,178","INFO","Supplying reward for 12.00 seconds"
"2016-10-01 11:49:27,083","INFO","Trial 46 - 11:49:27 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_17.wav"
"2016-10-01 11:50:27,164","INFO","Trial 47 - 11:50:27 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_7.wav"
"2016-10-01 11:50:27,228","INFO","Trial 48 - 11:50:27 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_2.wav"
"2016-10-01 11:50:47,442","INFO","Trial 49 - 11:50:47 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_12.wav"
"2016-10-01 11:51:08,564","INFO","Trial 50 - 11:51:08 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_1.wav"
"2016-10-01 11:51:08,615","INFO","Trial 51 - 11:51:08 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_11.wav"
"2016-10-01 11:51:08,698","INFO","Trial 52 - 11:51:08 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_1.wav"
"2016-10-01 11:51:21,048","INFO","Trial 53 - 11:51:21 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_8.wav"
"2016-10-01 11:51:21,116","INFO","Trial 54 - 11:51:21 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_1.wav"
"2016-10-01 11:51:30,276","INFO","Trial 55 - 11:51:30 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_9.wav"
"2016-10-01 11:51:30,750","INFO","Trial 56 - 11:51:30 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_17.wav"
"2016-10-01 11:51:42,338","INFO","Trial 57 - 11:51:42 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_11.wav"
"2016-10-01 11:51:58,115","INFO","Trial 58 - 11:51:58 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_1.wav"
"2016-10-01 11:51:58,407","INFO","Trial 59 - 11:51:58 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_2.wav"
"2016-10-01 11:51:58,469","INFO","Trial 60 - 11:51:58 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_2.wav"
"2016-10-01 11:52:25,798","INFO","Trial 61 - 11:52:25 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_8.wav"
"2016-10-01 11:52:25,980","INFO","Trial 62 - 11:52:25 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_2.wav"
"2016-10-01 11:52:40,105","INFO","Trial 63 - 11:52:40 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_12.wav"
"2016-10-01 11:52:40,230","INFO","Trial 64 - 11:52:40 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_12.wav"
"2016-10-01 11:52:40,471","INFO","Trial 65 - 11:52:40 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_7.wav"
"2016-10-01 11:52:40,644","INFO","Trial 66 - 11:52:40 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_10.wav"
"2016-10-01 11:53:04,410","INFO","Trial 67 - 11:53:04 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_1.wav"
"2016-10-01 11:53:05,788","INFO","Trial 68 - 11:53:05 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_10.wav"
"2016-10-01 11:53:05,862","INFO","Trial 69 - 11:53:05 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_11.wav"
"2016-10-01 11:53:32,887","INFO","Trial 70 - 11:53:32 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_9.wav"
"2016-10-01 11:53:38,897","INFO","Supplying reward for 12.00 seconds"
"2016-10-01 11:55:13,804","INFO","Trial 71 - 11:55:13 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_12.wav"
"2016-10-01 11:55:13,872","INFO","Trial 72 - 11:55:13 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_9.wav"
"2016-10-01 11:55:19,883","INFO","Supplying reward for 12.00 seconds"
"2016-10-01 11:56:38,459","INFO","Trial 73 - 11:56:38 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_12.wav"
"2016-10-01 11:56:38,521","INFO","Trial 74 - 11:56:38 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_7.wav"
"2016-10-01 11:56:38,712","INFO","Trial 75 - 11:56:38 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_2.wav"
"2016-10-01 11:56:38,893","INFO","Trial 76 - 11:56:38 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TH_Stim_1.wav"
"2016-10-01 11:56:55,125","INFO","Trial 77 - 11:56:55 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_2.wav"
"2016-10-01 11:56:55,190","INFO","Trial 78 - 11:56:55 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_8.wav"
"2016-10-01 11:56:55,284","INFO","Trial 79 - 11:56:55 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_12.wav"
"2016-10-01 11:57:06,778","INFO","Trial 80 - 11:57:06 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_2.wav"
"2016-10-01 11:57:07,798","INFO","Trial 81 - 11:57:07 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_11.wav"
"2016-10-01 11:57:21,658","INFO","Trial 82 - 11:57:21 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_10.wav"
"2016-10-01 11:57:21,875","INFO","Trial 83 - 11:57:21 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_10.wav"
"2016-10-01 11:57:22,094","INFO","Trial 84 - 11:57:22 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_8.wav"
"2016-10-01 11:57:23,180","INFO","Trial 85 - 11:57:23 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_17.wav"
"2016-10-01 11:57:47,589","INFO","Trial 86 - 11:57:47 - Rewarded - /home/fet/stimuli/shaping_categories_all/reward/DC_Stim_9.wav"
"2016-10-01 11:57:47,677","INFO","Trial 87 - 11:57:47 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_1.wav"
"2016-10-01 11:58:01,170","INFO","Trial 88 - 11:58:01 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_12.wav"
"2016-10-01 11:58:01,238","INFO","Trial 89 - 11:58:01 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_1.wav"
"2016-10-01 11:58:11,352","INFO","Trial 90 - 11:58:11 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_11.wav"
"2016-10-01 11:58:11,421","INFO","Trial 91 - 11:58:11 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_2.wav"
"2016-10-01 11:58:11,518","INFO","Trial 92 - 11:58:11 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/NC_Stim_12.wav"
"2016-10-01 11:58:11,964","INFO","Trial 93 - 11:58:11 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/WH_Stim_1.wav"
"2016-10-01 11:58:43,639","INFO","Trial 94 - 11:58:43 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/AG_Stim_11.wav"
"2016-10-01 11:58:43,703","INFO","Trial 95 - 11:58:43 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_1.wav"
"2016-10-01 11:58:44,688","INFO","Trial 96 - 11:58:44 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_11.wav"
"2016-10-01 11:58:44,760","INFO","Trial 97 - 11:58:44 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/DI_Stim_12.wav"
"2016-10-01 11:58:44,977","INFO","Trial 98 - 11:58:44 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/SO_Stim_10.wav"
"2016-10-01 11:58:45,084","INFO","Trial 99 - 11:58:45 - Unrewarded - /home/fet/stimuli/shaping_categories_all/nonreward/TE_Stim_2.wav"
"2016-10-01 11:58:46,146","INFO","Finishing session 1 at Sat Oct  1 11:58:46 2016"
"2016-10-01 11:58:46,146","INFO","Finished all sessions."
"2016-10-01 11:58:46,461","INFO","Exiting Session state"
"2016-10-01 11:58:46,461","CRITICAL","IOError('close() called during concurrent operation on the same file object.',)"
"2016-10-01 11:58:46,461","INFO","Exiting Idle state"
"2016-10-01 11:58:46,461","CRITICAL","IOError('close() called during concurrent operation on the same file object.',)"
"2016-10-01 11:58:46,468","ERROR","Unhandled exception: Traceback (most recent call last):
  File "/home/fet/scripts/pecking_test", line 171, in <module>
    args.func(args)
  File "/home/fet/scripts/pecking_test", line 15, in run
    run_pecking_test(args)
  File "/home/fet/python_path/pyoperant/tlab/pecking_test.py", line 192, in run_pecking_test
    exp.run()
  File "/home/fet/python_path/pyoperant/behavior/base.py", line 548, in run
    self._idle.start()
  File "/home/fet/python_path/pyoperant/states.py", line 95, in start
    state.run()
  File "/home/fet/python_path/pyoperant/states.py", line 180, in run
    return self.experiment.session.start()
  File "/home/fet/python_path/pyoperant/states.py", line 95, in start
    state.run()
  File "/home/fet/python_path/pyoperant/states.py", line 137, in run
    self.experiment.session_main()
  File "/home/fet/python_path/pyoperant/behavior/base.py", line 572, in session_main
    trial.run()
  File "/home/fet/python_path/pyoperant/trials.py", line 117, in run
    self.experiment.response_main()
  File "/home/fet/python_path/pyoperant/behavior/go_no_go_interrupt.py", line 141, in response_main
    self.panel.speaker.stop()
  File "/home/fet/python_path/pyoperant/components.py", line 587, in stop
    return self.output.stop(event=self.event)
  File "/home/fet/python_path/pyoperant/hwio.py", line 431, in stop
    return self.interface._stop_wav(event=event, **self.params)
  File "/home/fet/python_path/pyoperant/interfaces/pyaudio_.py", line 155, in _stop_wav
    self.wf.close()
  File "/home/fet/anaconda2/envs/pecking_test/lib/python2.7/wave.py", line 187, in close
    file.close()
IOError: close() called during concurrent operation on the same file object.
"
`
